# netlify.toml

[build]
  base = "frontend"               # Directory where your frontend code is located
  publish = "frontend/build"      # Build output directory

# Add more configuration options as needed
