[build]
  base = "/Users/dannygold/Documents/GitHub/AWS-Terraform-Project/frontend/my-app"               # Directory where your frontend code is located
  publish = "/Users/dannygold/Documents/GitHub/AWS-Terraform-Project/frontend/my-app/.next"     # The .next folder with production assets
